import { Inter } from 'next/font/google';
import { Roboto } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const roboto = Roboto({ subsets: ['latin'], weight: '500' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
